version: '2'
services:
  postgresql:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
    - ~/volumes/jhipster/user/postgresql/:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
    - 5432:5432
  user-service:
    container_name: user-service
    image: openjdk:8
    depends_on:
    - postgresql
    volumes:
    - .target/${APP_JAR}:/usr/src/user.jar
    working_dir: /usr/src
    command: bash -c "cd /usr/src && java -jar user.jar"
    stdin_open: true
    tty: true
    ports:
    - 8080:8080
    environment:
      - APP_JAR=${APP_JAR}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - ROOT_DEBUG_LEVEL=${ROOT_DEBUG_LEVEL}
      - PACKAGE_DEBUG_LEVEL=${PACKAGE_DEBUG_LEVEL}
      - HIBERNATE_DEBUG_LEVEL=${HIBERNATE_DEBUG_LEVEL}
      - WEB_DEBUG_LEVEL=${WEB_DEBUG_LEVEL}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}




